# Sample code of adjacency matrix and adjacency list in graph with networkx
## Install the necessary python libraries

In [62]:
!pip install networkx pandas numpy

## Generate adjacency dense matrix of directed graph

In [63]:
import networkx as nx
import numpy as np
import pandas as pd

# Instantiate the graph
G = nx.DiGraph()
# add node/edge pairs
G.add_edges_from([("A", "B"), ("B", "A"), ("C", "B"), ("C", "D")])
# 2D array adjacency matrix
A = nx.adjacency_matrix(G)
A_dense = A.todense()
print(A_dense)
# Pandas format of adjacency matrix
nx.to_pandas_adjacency(G)

[[0 1 0 0]
 [1 0 0 0]
 [0 1 0 1]
 [0 0 0 0]]


A    B    C    D
A  0.0  1.0  0.0  0.0
B  1.0  0.0  0.0  0.0
C  0.0  1.0  0.0  1.0
D  0.0  0.0  0.0  0.0

## Calculate the number of IN-edges, OUT-edges, add edge and remove edge.

In [64]:
# Instantiate the graph
G = nx.DiGraph()
# add node/edge pairs
G.add_edges_from([("A", "B"), ("B", "A"), ("C", "B"), ("C", "D")])

# Get a vertex’s out-edges:
print(f"OUT-edges of node B: {G.out_degree('B')}")
# Get a vertex’s in-edges: 
print(f"IN-edges of node B: {G.in_degree('B')}")
# Decide if some edge exists: 
print(f"Check an edge from A to C: {G.has_edge('A', 'C')}")
# Insert an edge:
G.add_edge("A", "C") 
# OR 
G.add_edges_from([("A", "D")])
print(f"Check an edge from A to C: {G.has_edge('A', 'C')}")
print(f"Check an edge from A to D: {G.has_edge('A', 'D')}")
# Delete an edge:
G.remove_edge("A", "C") 
# OR 
G.remove_edges_from([("A", "D")])
print(f"Check an edge from A to C: {G.has_edge('A', 'C')}")
print(f"Check an edge from A to D: {G.has_edge('A', 'D')}")

OUT-edges of node B: 1
IN-edges of node B: 2
Check an edge from A to C: False
Check an edge from A to C: True
Check an edge from A to D: True
Check an edge from A to C: False
Check an edge from A to D: False


## Display adjacency list of a directed graph

In [65]:
# Instantiate the graph
G = nx.DiGraph()
# add node/edge pairs
G.add_edges_from([("A", "B"), ("B", "A"), ("C", "B"), ("C", "D")])
adjacency_list = nx.generate_adjlist(G)
for line in adjacency_list:
    print(line)

A B
B A
C B D
D


## Display sparse and dense adjacency matrix of a directed graph

In [66]:
# Instantiate the graph
G = nx.DiGraph()
# add node/edge pairs
G.add_edges_from([(0, 1), (1, 0), (2, 1), (2, 3)])

adjacency_list = nx.generate_adjlist(G)
for line in adjacency_list:
    print(line)

A = nx.adjacency_matrix(G)
print(A)

# Pandas format of adjacency matrix
nx.to_pandas_adjacency(G)

0 1
1 0
2 1 3
3
  (0, 1)	1
  (1, 0)	1
  (2, 1)	1
  (2, 3)	1


0    1    2    3
0  0.0  1.0  0.0  0.0
1  1.0  0.0  0.0  0.0
2  0.0  1.0  0.0  1.0
3  0.0  0.0  0.0  0.0

## Display adjacency list, sparse and dense adjacency matrix of an undirected graph

In [67]:
# Instantiate the graph
G = nx.Graph()
# add node/edge pairs
G.add_edges_from([(0, 1), (1, 0), (2, 1), (2, 3)])
# Adjacency list
adjacency_list = nx.generate_adjlist(G)
for line in adjacency_list:
    print(line)
    
A = nx.adjacency_matrix(G)
print(A)
    
nx.to_pandas_adjacency(G)

0 1
1 2
2 3
3
  (0, 1)	1
  (1, 0)	1
  (1, 2)	1
  (2, 1)	1
  (2, 3)	1
  (3, 2)	1


0    1    2    3
0  0.0  1.0  0.0  0.0
1  1.0  0.0  1.0  0.0
2  0.0  1.0  0.0  1.0
3  0.0  0.0  1.0  0.0

## Weighted graph

In [68]:
# Instantiate the graph
G = nx.DiGraph()
# add node/edge pairs
G.add_weighted_edges_from([("A", "B", 1.5), ("B", "A", 1.5), ("C", "B", 3), ("C", "D", 2.5)])
# 2D array adjacency matrix
A = nx.adjacency_matrix(G)
A_dense = A.todense()
print(A_dense)
# Pandas format of adjacency matrix
nx.to_pandas_adjacency(G)

[[0.  1.5 0.  0. ]
 [1.5 0.  0.  0. ]
 [0.  3.  0.  2.5]
 [0.  0.  0.  0. ]]


A    B    C    D
A  0.0  1.5  0.0  0.0
B  1.5  0.0  0.0  0.0
C  0.0  3.0  0.0  2.5
D  0.0  0.0  0.0  0.0

In [69]:
import numpy as np
# Instantiate the graph
G = nx.DiGraph()
G.add_nodes_from([1,2,3,4,5])

# Define rows, columns and weighted values of the graph
rows    = [1, 1, 2, 2, 4, 4]
columns = [3, 5, 3, 4, 2, 3]
values  = [3, 4, 5, 7, 2, 6]

edges = zip(rows, columns, values)

G.add_weighted_edges_from(list(edges))


# 2D array adjacency matrix
A = nx.adjacency_matrix(G)
A_dense = A.todense()
print(A_dense)
# Pandas format of adjacency matrix
nx.to_pandas_adjacency(G)

[[0 0 3 0 4]
 [0 0 5 7 0]
 [0 0 0 0 0]
 [0 2 6 0 0]
 [0 0 0 0 0]]


1    2    3    4    5
1  0.0  0.0  3.0  0.0  4.0
2  0.0  0.0  5.0  7.0  0.0
3  0.0  0.0  0.0  0.0  0.0
4  0.0  2.0  6.0  0.0  0.0
5  0.0  0.0  0.0  0.0  0.0

# Neo4j Example Scripts
### Note: you should install Neo4j database in your computer and run these scripts in its UI application.

### Add entities into graph database.

In [ ]:
CREATE(:Book{name:'Graph Databases',published_date:'Nov 16, 2015'})
CREATE(:Person{name:'John',born:'Mar 8, 1998',linkedin:'@john'})
CREATE(:Person{name:'Sally',born:'Oct 16, 1997',linkedin:'@sali'})

## Add relations

In [ ]:
MATCH (a:Person), (b:Person) WHERE (a.name = 'John' AND b.name = 'Sally') CREATE (a)-[r1:IS_FRIENDS_WITH]->(b);
MATCH (a:Person), (b:Book) WHERE (a.name = 'John' OR a.name = 'Sally') AND b.name='Graph Databases' CREATE (a)-[r2:HAS_READ]->(b)

## Delete relationships

In [ ]:
MATCH (n:Person {name: 'John'})-[r:IS_FRIENDS_WITH]->() DELETE r


## Delete entities
You should remove all the relations connected to these entities before removing them

In [ ]:
MATCH (n:Person {name: 'John'})-[r:HAS_READ]->() DELETE r

MATCH (n:Person {name: 'John'}) DELETE n