# Sample code of adjacency matrix and adjacency list in graph with networkx
## Install the necessary python libraries

In [15]:
!pip install networkx pandas numpy

## Generate adjacency dense matrix of directed graph

In [10]:
import networkx as nx
import numpy as np
import pandas as pd

# Instantiate the graph
G = nx.DiGraph()
# add node/edge pairs
G.add_edges_from([("A", "B"), ("B", "A"), ("C", "B"), ("C", "D")])
# 2D array adjacency matrix
A = nx.adjacency_matrix(G)
A_dense = A.todense()
print(A_dense)
# Pandas format of adjacency matrix
nx.to_pandas_adjacency(G)

[[0 1 0 0]
 [1 0 0 0]
 [0 1 0 1]
 [0 0 0 0]]


A    B    C    D
A  0.0  1.0  0.0  0.0
B  1.0  0.0  0.0  0.0
C  0.0  1.0  0.0  1.0
D  0.0  0.0  0.0  0.0

## Calculate the number of IN-edges, OUT-edges, add edge and remove edge.

In [6]:
# Instantiate the graph
G = nx.DiGraph()
# add node/edge pairs
G.add_edges_from([("A", "B"), ("B", "A"), ("C", "B"), ("C", "D")])

# Get a vertex’s out-edges:
print(f"OUT-edges of node B: {G.out_degree('B')}")
# Get a vertex’s in-edges: 
print(f"IN-edges of node B: {G.in_degree('B')}")
# Decide if some edge exists: 
print(f"Check an edge from A to C: {G.has_edge('A', 'C')}")
# Insert an edge:
G.add_edge("A", "C") 
# OR 
G.add_edges_from([("A", "D")])
print(f"Check an edge from A to C: {G.has_edge('A', 'C')}")
print(f"Check an edge from A to D: {G.has_edge('A', 'D')}")
# Delete an edge:
G.remove_edge("A", "C") 
# OR 
G.remove_edges_from([("A", "D")])
print(f"Check an edge from A to C: {G.has_edge('A', 'C')}")
print(f"Check an edge from A to D: {G.has_edge('A', 'D')}")

OUT-edges of node B: 1
IN-edges of node B: 2
Check an edge from A to C: False
Check an edge from A to C: True
Check an edge from A to D: True
Check an edge from A to C: False
Check an edge from A to D: False


## Display adjacency list of a directed graph

In [16]:
# Instantiate the graph
G = nx.DiGraph()
# add node/edge pairs
G.add_edges_from([("A", "B"), ("B", "A"), ("C", "B"), ("C", "D")])
adjacency_list = nx.generate_adjlist(G)
for line in adjacency_list:
    print(line)

A B
B A
C B D
D


## Display sparse and dense adjacency matrix of a directed graph

In [24]:
# Instantiate the graph
G = nx.DiGraph()
# add node/edge pairs
G.add_edges_from([(0, 1), (1, 0), (2, 1), (2, 3)])

adjacency_list = nx.generate_adjlist(G)
for line in adjacency_list:
    print(line)

A = nx.adjacency_matrix(G)
print(A)

# Pandas format of adjacency matrix
nx.to_pandas_adjacency(G)

0 1
1 0
2 1 3
3
  (0, 1)	1
  (1, 0)	1
  (2, 1)	1
  (2, 3)	1


0    1    2    3
0  0.0  1.0  0.0  0.0
1  1.0  0.0  0.0  0.0
2  0.0  1.0  0.0  1.0
3  0.0  0.0  0.0  0.0

## Display adjacency list, sparse and dense adjacency matrix of an undirected graph

In [25]:
# Instantiate the graph
G = nx.Graph()
# add node/edge pairs
G.add_edges_from([(0, 1), (1, 0), (2, 1), (2, 3)])
# Adjency list
adjacency_list = nx.generate_adjlist(G)
for line in adjacency_list:
    print(line)
    
A = nx.adjacency_matrix(G)
print(A)
    
nx.to_pandas_adjacency(G)

0 1
1 2
2 3
3
  (0, 1)	1
  (1, 0)	1
  (1, 2)	1
  (2, 1)	1
  (2, 3)	1
  (3, 2)	1


0    1    2    3
0  0.0  1.0  0.0  0.0
1  1.0  0.0  1.0  0.0
2  0.0  1.0  0.0  1.0
3  0.0  0.0  1.0  0.0